### ISSUE TITLE
Module 4 setup: TRF

### ISSUE THREAD

**Issue by ccarlos-shanley** [mdsufz/MuDoGeR#10]
Hi, I am having issue completing the Maker2 installation. I get the following message after perl ./configure (Step 13):
"The full path including the name for the TRF program.
TRF_PRGM:
"

What is TRF? There is no mention of that during the installing process.

Thank you

**Comment by JotaKas** [comment]
Hey, ccarlos-shanley,

TRF is a dependency used by MAKER2 and should have been automatically installed after you first used the install.sh script and installed all the dependencies for module 4.

If your initial module 4 installation was successful, you should have the maker2_env available.
Before running the `perl ./configure`, you should make sure you have the maker2_env environment activated. If it is activated, the TRF path should be automatically found. 

If you have the maker2_env created by MuDoGeR during the installation process, I suggest you delete it and try running the install.sh again following the installation instructions. Later, you should try to do [genemark and maker2 installations](https://github.com/mdsufz/MuDoGeR/blob/master/installation/genemark_maker2_installation.md#finish-module-4-installation). Make sure that you have the created maker2_env activated before running the ./configure.

If that did not work, you could follow the instructions [here](https://github.com/mdsufz/MuDoGeR/blob/master/understand_main_outputs.md#using-the-tools-independently). To activate your maker2_env manually and install the TRF dependency by running `conda install -y bioconda::trf` with the maker2_env activated. After that, the TRF path should be found when you run the `perl ./configure`.
