### ISSUE TITLE
Mudoger preprocess never starts

### ISSUE THREAD

**Issue by bramvandijk88** [mdsufz/MuDoGeR#12]
Given what I've seen other people post, I feel like the module "preprocess" in my data actually never starts. Like another person already raised, I get an error

```
Traceback (most recent call last):
  File "/home/vandijk/anaconda3/envs/mudoger_env/dependencies/mdcheck.py", line 21, in <module>
    id,filepath,group=l.strip().split(sep)
ValueError: not enough values to unpack (expected 3, got 2)
```

After which the module only prints

`mudoger preprocess`

And then appears to just turn into a ghost. There are no further prints, and it has been like this for 48 hours.

**Comment by JotaKas** [comment]
Dear bramvandijk,

We are solving this and other bugs identified. Soon an update is coming. Thank you for your issue.

However, the error

File "/home/yankuo/miniconda3/envs/mudoger_env/dependencies/mdcheck.py", line 21, in
id,filepath,group=l.strip().split(sep)
ValueError: not enough values to unpack (expected 3, got 2)

regards only the metadata table validation.

The mdcheck.py script works to check if your metadata table is properly formatted, and does not break the rest of the pipeline. Therefore, if the pipeline did not start immediately, please make sure your metadata table is properly formatted as described in the manual.

Soon we will correct the mdcheck.py and include a more helpful error report. 

You can also try to delete the mudoger_env environment and install it again. In the next days, I will upload a bug fix that includes changes in the installation and running. Thank you for the report

**Comment by mherold1** [comment]
I ran in the same problem and for me the issue was related to having the reads named correctly (`sample_1.fastq sample_2.fastq`), which is a requirement for metawrap later on.
When I ran the module1 command without the `-m` option it seemed to be stuck at `mudoger preprocess`, when I ran it with the `-m` option it reported some errors, something like malformatted fastq

**Comment by nksjplai** [comment]
I witnessed the same issue, please rectify.

**Comment by JotaKas** [comment]
Allow me to understand your data.

The problem with the -m flag was fixed in version 1.0.1. The installation procedure should also be faster.
Please, try to delete the mudoger_env environment, clone, and install the new version from the tool.

To try to fix your problem with the missing QC files. Please, try to give the complete path to your output folder when calling the mudoger. 

this means `` mudoger --module .... ... ... -o /complete/path/to/your/output_folder ... ....``

Let me know how it went.

**Comment by nksjplai** [comment]
HI MuDoGer Team,

Below is the screenshot of the terminal

1) My version is  1.0.1
2) Even the memory given is 196GB,  during the assembly run it shows -m 0
3) Final_pure_reads were never created, I checked the folders.
4) Don’t get carried away with the “assembly already exist”, I reran the program after deleting the output , it still gives me the error.


Please give me your cell number if possible I can call to resolve the issue in realtime.

***@***.***


with regards

Dr. Nitin Kumar Singh
Scientist
California Institute of Technology, NASA-Jet Propulsion Laboratory(JPL)
Biotechnology and Planetary Protection Group; M/S 245-104
4800 Oak Grove Dr., Pasadena, CA 91109
Office:  +1 (818) 354 5799<tel:(818)%20354-5799>
Fax:     +1 (818) 354-4176
Email: ***@***.******@***.***>
Web: https://planetaryprotection.jpl.nasa.gov/singh-bio

Caltech | Institutional Review Board
Caltech | Institutional Animal Care and Use Committee
Caltech | Institutional Biosafety Committee



From: Jonas C K ***@***.***>
Sent: Wednesday, July 27, 2022 12:46 AM
To: mdsufz/MuDoGeR ***@***.***>
Cc: Singh, Nitin K (US 353N) ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL] Re: [mdsufz/MuDoGeR] Mudoger preprocess never starts (Issue #12)


Allow me to understand your data.

The problem with the -m flag was fixed in version 1.0.1. The installation procedure should also be faster.
Please, try to delete the mudoger_env environment, clone, and install the new version from the tool.

To try to fix your problem with the missing QC files. Please, try to give the complete path to your output folder when calling the mudoger.

this means mudoger --module .... ... ... -o /complete/path/to/your/output_folder ... ....

Let me know how it went.

**Comment by yankuosun** [comment]
HI MuDoGer Team,
I also encountered this problem. Final_pure_reads were never created, I checked the folders. the paths of the result creation was not right， and the log file  presented"metawrap read_qc --skip-bmtagger -1 -2 -2 -t 20 -o result/home/yankuo/database1/22R05962_R_1.fastq/qc " .  I checked the software and found all the packages were installed successfully. my twitter is yankuo5,  I had spend two months trying to figure this and its dependencies, I would like to send my remote code to check this problem.

**Comment by yankuosun** [comment]
mudoger --module preprocess --meta 1.tsv -o /home/yankuo/database1/result/ -t 20 -m 100


        ███    ███ ██    ██ ██████   ██████   ██████  ███████ ██████
        ████  ████ ██    ██ ██   ██ ██    ██ ██       ██      ██   ██
        ██ ████ ██ ██    ██ ██   ██ ██    ██ ██   ███ █████   ██████
        ██  ██  ██ ██    ██ ██   ██ ██    ██ ██    ██ ██      ██   ██
        ██      ██  ██████  ██████   ██████   ██████  ███████ ██   ██
                        Multi-Domain Genome Recovery
                                Version 1.0.1


mudoger preprocess
-> Running QC
---------- STARTING MODULE 1-1 QC
-> Running khmer pred
---------- STARTING MODULE 1-2 KMER

|| This is the script unique-kmers.py in khmer.
|| You are running khmer version 2.1.1
|| You are also using screed version 1.0.4
||
|| If you use this script in a publication, please cite EACH of the following:
||
||   * MR Crusoe et al., 2015. http://dx.doi.org/10.12688/f1000research.6924.1
||   * A. Döring et al. http://dx.doi.org:80/10.1186/1471-2105-9-11
||   * Irber and Brown. http://dx.doi.org/10.1101/056846
||
|| Please see http://khmer.readthedocs.io/en/latest/citations.html for details.

Traceback (most recent call last):
  File "/home/yankuo/miniconda3/envs/mudoger_env/dependencies/conda/envs/metawrap_env/bin/unique-kmers.py", line 165, in <module>
    main()
  File "/home/yankuo/miniconda3/envs/mudoger_env/dependencies/conda/envs/metawrap_env/bin/unique-kmers.py", line 140, in main
    stream_records=args.stream_records)
OSError: File /home/yankuo/database1/result//﻿22R0E/qc/final_pure_reads_1.fastq contains badly formatted sequence or does not exist.

|| This is the script unique-kmers.py in khmer.
|| You are running khmer version 2.1.1
|| You are also using screed version 1.0.4
||
|| If you use this script in a publication, please cite EACH of the following:
||
||   * MR Crusoe et al., 2015. http://dx.doi.org/10.12688/f1000research.6924.1
||   * A. Döring et al. http://dx.doi.org:80/10.1186/1471-2105-9-11
||   * Irber and Brown. http://dx.doi.org/10.1101/056846
||
|| Please see http://khmer.readthedocs.io/en/latest/citations.html for details.

Traceback (most recent call last):
  File "/home/yankuo/miniconda3/envs/mudoger_env/dependencies/conda/envs/metawrap_env/bin/unique-kmers.py", line 165, in <module>
    main()
  File "/home/yankuo/miniconda3/envs/mudoger_env/dependencies/conda/envs/metawrap_env/bin/unique-kmers.py", line 140, in main
    stream_records=args.stream_records)
OSError: File /home/yankuo/database1/result//﻿22R0E/qc/final_pure_reads_1.fastq contains badly formatted sequence or does not exist.
Error in if (kmer_55_unique > 0) { : 需要TRUE/FALSE值的地方不可以用缺少值
Calls: as.data.frame -> t -> apply -> FUN
停止执行
cat: metaspades_prediction.tsv: 没有那个文件或目录
/home/yankuo/database1
“end predict_mem_input”
2022年 10月 13日 星期四 12:13:02 CST
-> Running assembly
metawrap assembly -1 /home/yankuo/database1/result//﻿22R0E/qc/final_pure_reads_1.fastq -2 /home/yankuo/database1/result//﻿22R0E/qc/final_pure_reads_2.fastq -m 0 -t 20 -o /home/yankuo/database1/result//﻿22R0E/assembly --metaspades
Warning: /home/yankuo/database1/result//﻿22R0E/assembly already exists.

########################################################################################################################
#####                                          ASSEMBLING WITH METASPADES                                          #####
########################################################################################################################


------------------------------------------------------------------------------------------------------------------------
-----              Using reads /home/yankuo/database1/result//﻿22R0E/qc/final_pure_reads_1.fastq and             -----
-----              /home/yankuo/database1/result//﻿22R0E/qc/final_pure_reads_2.fastq for assembly,               -----
------------------------------------------------------------------------------------------------------------------------


************************************************************************************************************************
*****             Read files /home/yankuo/database1/result//﻿22R0E/qc/final_pure_reads_1.fastq and/or            *****
*****           /home/yankuo/database1/result//﻿22R0E/qc/final_pure_reads_2.fastq dont exist. Exiting.           *****
************************************************************************************************************************


real    0m0.044s
user    0m0.022s
sys     0m0.021s
--> Assembly didn't work. Please check your resources
-> module 1 (preprocess and assembly) is finished
-> Running QC
---------- STARTING MODULE 1-1 QC
-> Running khmer pred
---------- STARTING MODULE 1-2 KMER

|| This is the script unique-kmers.py in khmer.
|| You are running khmer version 2.1.1
|| You are also using screed version 1.0.4
||
|| If you use this script in a publication, please cite EACH of the following:
||
||   * MR Crusoe et al., 2015. http://dx.doi.org/10.12688/f1000research.6924.1
||   * A. Döring et al. http://dx.doi.org:80/10.1186/1471-2105-9-11
||   * Irber and Brown. http://dx.doi.org/10.1101/056846
||
|| Please see http://khmer.readthedocs.io/en/latest/citations.html for details.

Traceback (most recent call last):
  File "/home/yankuo/miniconda3/envs/mudoger_env/dependencies/conda/envs/metawrap_env/bin/unique-kmers.py", line 165, in <module>
    main()
  File "/home/yankuo/miniconda3/envs/mudoger_env/dependencies/conda/envs/metawrap_env/bin/unique-kmers.py", line 140, in main
    stream_records=args.stream_records)
OSError: File /home/yankuo/database1/result//home/yankuo/database1/22R05962_R_1.fastq/qc/final_pure_reads_1.fastq contains badly formatted sequence or does not exist.

|| This is the script unique-kmers.py in khmer.
|| You are running khmer version 2.1.1
|| You are also using screed version 1.0.4
||
|| If you use this script in a publication, please cite EACH of the following:
||
||   * MR Crusoe et al., 2015. http://dx.doi.org/10.12688/f1000research.6924.1
||   * A. Döring et al. http://dx.doi.org:80/10.1186/1471-2105-9-11
||   * Irber and Brown. http://dx.doi.org/10.1101/056846
||
|| Please see http://khmer.readthedocs.io/en/latest/citations.html for details.

Traceback (most recent call last):
  File "/home/yankuo/miniconda3/envs/mudoger_env/dependencies/conda/envs/metawrap_env/bin/unique-kmers.py", line 165, in <module>
    main()
  File "/home/yankuo/miniconda3/envs/mudoger_env/dependencies/conda/envs/metawrap_env/bin/unique-kmers.py", line 140, in main
    stream_records=args.stream_records)
OSError: File /home/yankuo/database1/result//home/yankuo/database1/22R05962_R_1.fastq/qc/final_pure_reads_1.fastq contains badly formatted sequence or does not exist.
Error in if (kmer_55_unique > 0) { : 需要TRUE/FALSE值的地方不可以用缺少值
Calls: as.data.frame -> t -> apply -> FUN
停止执行
cat: metaspades_prediction.tsv: 没有那个文件或目录
/home/yankuo/database1
“end predict_mem_input”
2022年 10月 13日 星期四 12:13:12 CST
-> Running assembly
metawrap assembly -1 /home/yankuo/database1/result//home/yankuo/database1/22R05962_R_1.fastq/qc/final_pure_reads_1.fastq -2 /home/yankuo/database1/result//home/yankuo/database1/22R05962_R_1.fastq/qc/final_pure_reads_2.fastq -m 0 -t 20 -o /home/yankuo/database1/result//home/yankuo/database1/22R05962_R_1.fastq/assembly --metaspades
Warning: /home/yankuo/database1/result//home/yankuo/database1/22R05962_R_1.fastq/assembly already exists.

########################################################################################################################
#####                                          ASSEMBLING WITH METASPADES                                          #####
########################################################################################################################


------------------------------------------------------------------------------------------------------------------------
-----                                                  Using reads                                                 -----
-----     /home/yankuo/database1/result//home/yankuo/database1/22R05962_R_1.fastq/qc/final_pure_reads_1.fastq      -----
-----                                                     and                                                      -----
-----     /home/yankuo/database1/result//home/yankuo/database1/22R05962_R_1.fastq/qc/final_pure_reads_2.fastq      -----
-----                                                for assembly,                                                 -----
------------------------------------------------------------------------------------------------------------------------


************************************************************************************************************************
*****                                                  Read files                                                  *****
*****     /home/yankuo/database1/result//home/yankuo/database1/22R05962_R_1.fastq/qc/final_pure_reads_1.fastq      *****
*****                                                    and/or                                                    *****
*****     /home/yankuo/database1/result//home/yankuo/database1/22R05962_R_1.fastq/qc/final_pure_reads_2.fastq      *****
*****                                             dont exist. Exiting.                                             *****
************************************************************************************************************************


real    0m0.046s
user    0m0.032s
sys     0m0.012s
--> Assembly didn't work. Please check your resources
-> module 1 (preprocess and assembly) is finished
-> Running QC
---------- STARTING MODULE 1-1 QC
-> Running khmer pred
---------- STARTING MODULE 1-2 KMER

|| This is the script unique-kmers.py in khmer.
|| You are running khmer version 2.1.1
|| You are also using screed version 1.0.4
||
|| If you use this script in a publication, please cite EACH of the following:
||
||   * MR Crusoe et al., 2015. http://dx.doi.org/10.12688/f1000research.6924.1
||   * A. Döring et al. http://dx.doi.org:80/10.1186/1471-2105-9-11
||   * Irber and Brown. http://dx.doi.org/10.1101/056846
||
|| Please see http://khmer.readthedocs.io/en/latest/citations.html for details.

Traceback (most recent call last):
  File "/home/yankuo/miniconda3/envs/mudoger_env/dependencies/conda/envs/metawrap_env/bin/unique-kmers.py", line 165, in <module>
    main()
  File "/home/yankuo/miniconda3/envs/mudoger_env/dependencies/conda/envs/metawrap_env/bin/unique-kmers.py", line 140, in main
    stream_records=args.stream_records)
OSError: File /home/yankuo/database1/result//22R0E/qc/final_pure_reads_1.fastq contains badly formatted sequence or does not exist.

|| This is the script unique-kmers.py in khmer.
|| You are running khmer version 2.1.1
|| You are also using screed version 1.0.4
||
|| If you use this script in a publication, please cite EACH of the following:
||
||   * MR Crusoe et al., 2015. http://dx.doi.org/10.12688/f1000research.6924.1
||   * A. Döring et al. http://dx.doi.org:80/10.1186/1471-2105-9-11
||   * Irber and Brown. http://dx.doi.org/10.1101/056846
||
|| Please see http://khmer.readthedocs.io/en/latest/citations.html for details.

Traceback (most recent call last):
  File "/home/yankuo/miniconda3/envs/mudoger_env/dependencies/conda/envs/metawrap_env/bin/unique-kmers.py", line 165, in <module>
    main()
  File "/home/yankuo/miniconda3/envs/mudoger_env/dependencies/conda/envs/metawrap_env/bin/unique-kmers.py", line 140, in main
    stream_records=args.stream_records)
OSError: File /home/yankuo/database1/result//22R0E/qc/final_pure_reads_1.fastq contains badly formatted sequence or does not exist.
Error in if (kmer_55_unique > 0) { : 需要TRUE/FALSE值的地方不可以用缺少值
Calls: as.data.frame -> t -> apply -> FUN
停止执行
cat: metaspades_prediction.tsv: 没有那个文件或目录
/home/yankuo/database1
“end predict_mem_input”
2022年 10月 13日 星期四 12:13:22 CST
-> Running assembly
metawrap assembly -1 /home/yankuo/database1/result//22R0E/qc/final_pure_reads_1.fastq -2 /home/yankuo/database1/result//22R0E/qc/final_pure_reads_2.fastq -m 0 -t 20 -o /home/yankuo/database1/result//22R0E/assembly --metaspades
Warning: /home/yankuo/database1/result//22R0E/assembly already exists.

########################################################################################################################
#####                                          ASSEMBLING WITH METASPADES                                          #####
########################################################################################################################


------------------------------------------------------------------------------------------------------------------------
-----               Using reads /home/yankuo/database1/result//22R0E/qc/final_pure_reads_1.fastq and               -----
-----                /home/yankuo/database1/result//22R0E/qc/final_pure_reads_2.fastq for assembly,                -----
------------------------------------------------------------------------------------------------------------------------


************************************************************************************************************************
*****              Read files /home/yankuo/database1/result//22R0E/qc/final_pure_reads_1.fastq and/or              *****
*****            /home/yankuo/database1/result//22R0E/qc/final_pure_reads_2.fastq dont exist. Exiting.             *****
************************************************************************************************************************


real    0m0.039s
user    0m0.015s
sys     0m0.023s
--> Assembly didn't work. Please check your resources
-> module 1 (preprocess and assembly) is finished
-> Running QC
---------- STARTING MODULE 1-1 QC
-> Running khmer pred
---------- STARTING MODULE 1-2 KMER

|| This is the script unique-kmers.py in khmer.
|| You are running khmer version 2.1.1
|| You are also using screed version 1.0.4
||
|| If you use this script in a publication, please cite EACH of the following:
||
||   * MR Crusoe et al., 2015. http://dx.doi.org/10.12688/f1000research.6924.1
||   * A. Döring et al. http://dx.doi.org:80/10.1186/1471-2105-9-11
||   * Irber and Brown. http://dx.doi.org/10.1101/056846
||
|| Please see http://khmer.readthedocs.io/en/latest/citations.html for details.

Traceback (most recent call last):
  File "/home/yankuo/miniconda3/envs/mudoger_env/dependencies/conda/envs/metawrap_env/bin/unique-kmers.py", line 165, in <module>
    main()
  File "/home/yankuo/miniconda3/envs/mudoger_env/dependencies/conda/envs/metawrap_env/bin/unique-kmers.py", line 140, in main
    stream_records=args.stream_records)
OSError: File /home/yankuo/database1/result//home/yankuo/database1/22R05962_R_2.fastq/qc/final_pure_reads_1.fastq contains badly formatted sequence or does not exist.

|| This is the script unique-kmers.py in khmer.
|| You are running khmer version 2.1.1
|| You are also using screed version 1.0.4
||
|| If you use this script in a publication, please cite EACH of the following:
||
||   * MR Crusoe et al., 2015. http://dx.doi.org/10.12688/f1000research.6924.1
||   * A. Döring et al. http://dx.doi.org:80/10.1186/1471-2105-9-11
||   * Irber and Brown. http://dx.doi.org/10.1101/056846
||
|| Please see http://khmer.readthedocs.io/en/latest/citations.html for details.

Traceback (most recent call last):
  File "/home/yankuo/miniconda3/envs/mudoger_env/dependencies/conda/envs/metawrap_env/bin/unique-kmers.py", line 165, in <module>
    main()
  File "/home/yankuo/miniconda3/envs/mudoger_env/dependencies/conda/envs/metawrap_env/bin/unique-kmers.py", line 140, in main
    stream_records=args.stream_records)
OSError: File /home/yankuo/database1/result//home/yankuo/database1/22R05962_R_2.fastq/qc/final_pure_reads_1.fastq contains badly formatted sequence or does not exist.
Error in if (kmer_55_unique > 0) { : 需要TRUE/FALSE值的地方不可以用缺少值
Calls: as.data.frame -> t -> apply -> FUN
停止执行
cat: metaspades_prediction.tsv: 没有那个文件或目录
/home/yankuo/database1
“end predict_mem_input”
2022年 10月 13日 星期四 12:13:31 CST
-> Running assembly
metawrap assembly -1 /home/yankuo/database1/result//home/yankuo/database1/22R05962_R_2.fastq/qc/final_pure_reads_1.fastq -2 /home/yankuo/database1/result//home/yankuo/database1/22R05962_R_2.fastq/qc/final_pure_reads_2.fastq -m 0 -t 20 -o /home/yankuo/database1/result//home/yankuo/database1/22R05962_R_2.fastq/assembly --metaspades
Warning: /home/yankuo/database1/result//home/yankuo/database1/22R05962_R_2.fastq/assembly already exists.

########################################################################################################################
#####                                          ASSEMBLING WITH METASPADES                                          #####
########################################################################################################################


------------------------------------------------------------------------------------------------------------------------
-----                                                  Using reads                                                 -----
-----     /home/yankuo/database1/result//home/yankuo/database1/22R05962_R_2.fastq/qc/final_pure_reads_1.fastq      -----
-----                                                     and                                                      -----
-----     /home/yankuo/database1/result//home/yankuo/database1/22R05962_R_2.fastq/qc/final_pure_reads_2.fastq      -----
-----                                                for assembly,                                                 -----
------------------------------------------------------------------------------------------------------------------------


************************************************************************************************************************
*****                                                  Read files                                                  *****
*****     /home/yankuo/database1/result//home/yankuo/database1/22R05962_R_2.fastq/qc/final_pure_reads_1.fastq      *****
*****                                                    and/or                                                    *****
*****     /home/yankuo/database1/result//home/yankuo/database1/22R05962_R_2.fastq/qc/final_pure_reads_2.fastq      *****
*****                                             dont exist. Exiting.                                             *****
************************************************************************************************************************


real    0m0.046s
user    0m0.034s
sys     0m0.010s
--> Assembly didn't work. Please check your resources
-> module 1 (preprocess and assembly) is finished

**Comment by yankuosun** [comment]
tree result
result
├── ﻿22R0E
│   ├── assembly
│   ├── khmer
│   │   ├── final_prediction.tsv
│   │   ├── input_for_predictR.tsv
│   │   ├── kmer-33
│   │   └── kmer-55
│   └── qc
│       └── log_qc
├── 22R0E
│   ├── assembly
│   ├── khmer
│   │   ├── final_prediction.tsv
│   │   ├── input_for_predictR.tsv
│   │   ├── kmer-33
│   │   └── kmer-55
│   └── qc
│       └── log_qc
└── home
    └── yankuo
        └── database1
            ├── 22R05962_R_1.fastq
            │   ├── assembly
            │   ├── khmer
            │   │   ├── final_prediction.tsv
            │   │   ├── input_for_predictR.tsv
            │   │   ├── kmer-33
            │   │   └── kmer-55
            │   └── qc
            │       └── log_qc
            └── 22R05962_R_2.fastq
                ├── assembly
                ├── khmer
                │   ├── final_prediction.tsv
                │   ├── input_for_predictR.tsv
                │   ├── kmer-33
                │   └── kmer-55
                └── qc
                    └── log_qc

**Comment by yankuosun** [comment]
22R0E   home/yankuo/database1/22R05962_R_1.fastq
22R0E   home/yankuo/database1/22R05962_R_2.fastq

**Comment by JotaKas** [comment]
Hey @yankuosun,

Can you make sure your input metadata table is formatted correctly?

It should be a tab-separated file. Your example shows that you used a simple space to separate the paths.

You can try using the following `awk -v OFS="\t" '$1=$1' meta > meta.tsv` to convert your simple space to a tab.
You can try deleting your outputs and running again with the corrected formatted metadata table.

Also, you can reach me at jona.kasmanas@ufz.de. We can perhaps schedule a quick call if you like.

**Comment by yankuosun** [comment]
Thanks，Jotakas，I'll test it first. Best Regards
