### ISSUE TITLE
only use one module 

### ISSUE THREAD

**Issue by Thexiyang** [mdsufz/MuDoGeR#19]
Thanks for the nice tool! If I only use Module 4 and my data were already produced by other tools,  what the metadata.tsv should be? And how I can tell the tool where my old data are?

**Comment by JotaKas** [comment]
Hey @Thexiyang,

In order for mudoger to run smoothly, it requires a specific folder structure. Module 4 requires the assembly file and your quality-controlled reads.

This means that for module 4 to run with the simple command, you should place your assembly file and your quality-controlled reads in the following structure:

output/path/
         └── sample_name
                 ├── assembly
                 │     └── final_assembly.fasta
                 └── qc
                         ├── final_pure_reads_1.fastq
                         └── final_pure_reads_2.fastq

Where the `output/path/` is the argument you give to the -o parameter.
sample_name is the name of your sample you give on the metadata.tsv file.

For your metadata.tsv file, you could give the sample name and the path to your quality-controlled reads, like such:

```
sample_name   /output/path/sample_name/qc/final_pure_reads_1.fastq
sample_name   /output/path/sample_name/qc/final_pure_reads_2.fastq
```
