### ISSUE TITLE
MuDoGeR wants to write to root paths

### ISSUE THREAD

**Issue by Mechah** [mdsufz/MuDoGeR#20]
Hi, thanks for providing MuDoGeR! It sound's great and easy to use.
However, when I want to give it a go on a few test samples I get permission denied errors, because MuDoGeR tries to write into root paths (e.g. /qc_log with preprocess or /viruses with module 3 and many more).
As I think it makes total sense, that root directories are protected from writing commands by any tool, I was wondering if I can change the settings of MuDoGeR so that these directories will be created in my output paths.
However, as there were no issues during the installation I'm not sure where to start.
Thanks for any help!
P.S. I'm running MuDoGeR 1.0.1

**Comment by JotaKas** [comment]
Hey Mechah.

Thanks for your contact. Would you mind sharing the errors specifically? 

Mudoger was designed to write its files only on the output folder the user has specified. If you have this problem, it may be some intermediate files from other tools or something else. If you could share your errors, I may be able to reproduce them and solve them.

Thanks again

**Comment by Mechah** [comment]
Hi,
here are the errors from the first steps of module 1. I get similar errors when I test other modules as well.

--------- STARTING MODULE 1-1 QC
mkdir: missing operand
Try 'mkdir --help' for more information.
bash: /log_qc: Permission denied
-> Running khmer pred
---------- STARTING MODULE 1-2 KMER
mkdir: cannot create directory ‘’: No such file or directory
usage: unique-kmers.py [--version] [--info] [-h] [-q] [-k KSIZE]
                       [-e ERROR_RATE] [-R filename] [-S] [--diagnostics]
                       input_sequence_filename [input_sequence_filename ...]
unique-kmers.py: error: argument -R/--report: can't open '/kmer-33': [Errno 13] Permission denied: '/kmer-33'
usage: unique-kmers.py [--version] [--info] [-h] [-q] [-k KSIZE]
                       [-e ERROR_RATE] [-R filename] [-S] [--diagnostics]
                       input_sequence_filename [input_sequence_filename ...]
unique-kmers.py: error: argument -R/--report: can't open '/kmer-55': [Errno 13] Permission denied: '/kmer-55'
bash: /input_for_predictR.tsv: Permission denied
cat: /kmer-33: No such file or directory
bash: /input_for_predictR.tsv: Permission denied
cat: /kmer-55: No such file or directory
bash: /input_for_predictR.tsv: Permission denied
cp: cannot create regular file '': No such file or directory
cp: cannot create regular file '': No such file or directory
cp: cannot create regular file '': No such file or directory
Fatal error: cannot open file 'mpred_predict.R': No such file or directory
cat: metaspades_prediction.tsv: No such file or directory
/proj/gibbons/2022_mahnert/MuDoGeR/testing
“end predict_mem_input”
Sat 27 Aug 2022 06:16:15 AM PDT
tail: cannot open '/final_prediction.tsv' for reading: No such file or directory
-> Running assembly

Thanks for your help!

**Comment by JotaKas** [comment]
Hey @Mechah,

Could you share the exact command you are using to call mudoger?

Thank again for sharing

**Comment by Mechah** [comment]
This is the exact command with full paths (executed within the conda environment of MuDoGeR:

mudoger --module preprocess --meta /proj/gibbons/2022_mahnert/MuDoGeR/test_HPV_v2/metadata.tsv -o /proj/gibbons/2022_mahnert/MuDoGeR/test_HPV_v2/ -t 10 --megahit -m 100

**Comment by JotaKas** [comment]
I am not able to replicate the problem. 

One possible problem is that your metadata table is badly formatted. Please, make sure it is a tab-separated file as described.
Soon, I will upload a 'metadata table checker script', so this may not happen again.

To ensure you have the proper format, you can separate your metadata columns by spaces and then run something like `awk -v OFS="\t" '$1=$1' file1`, if you have awk available. 

If that is the case, MuDoGeR may falsely read the name of your sample and create some problems. 
Are you using the GitHub cloned directory for your outputs? I don't see why this may be a problem, but if that is the case, try using a different directory.

Let me know how it goes.
